import React from "react";
import Head from "next/head";

function HomePage() {
	return <React.Fragment>
		<Head>
		<title>HTML Table Style Generator by eli geske</title>
		</Head>
		<div id="container"
			dangerouslySetInnerHTML={{
				__html: `
				<div id="titleText" style="position: absolute; width: 581px; padding: 10px 22px;">
				<h1 style="margin: 0 0 10px 0;">HTML Table Style Generator <span
								style="color: #CCCCCC; font-style: italic;">by eli geske</span></h1>
				<p>Style an HTML table using CSS with this easy tool! <br />
						Select from preset color settings from the bottom, or set your own theme with the controls on the right.
						Once finished the HTML and CSS will be generated by pressing the tabs just above the Table.<br />
						<strong>NOTE</strong>: IE8 and below will not see the rounded corners.
				</p>
				<p>Using CSS2, CSS3 techniques that are cross browser compatible. Easy to use, just choose the settings to
						the right then hit the generate button and your css and html is generated. From table padding, border,
						alternating row colors, and gradients. It's all at your finger tips.</p>
				<p style="display: none;">CSS is pretty much the best option you have to styling or creating a table theme.
						It maybe easy, yes, but having to make a good theme visually takes quite the time. Imagine always having
						to click refesh after design, or using other environments to style them. Sure some of the environments
						are great, but having tools all bundled up for specific reasons is more time efficient. </p>

		</div>
		<div id="sidebar1">
				<form id="vars">
						<div>
								<table style="text-align: left;">
										<tr>
												<td colspan="2">
														<label>Font:</label>
														<select id="font">
																<option>Arial, Helvetica, sans-serif</option>
																<option>Times New Roman, Times, serif</option>
																<option>Courier New, Courier, monospace</option>
																<option>Georgia, Times New Roman, Times, serif</option>
																<option>Verdana, Arial, Helvetica, sans-serif</option>
																<option>Geneva, Arial, Helvetica, sans-serif</option>
														</select>
												</td>
										</tr>
										<tr>
												<td width="50%">
														<label>Border-Size: <input type="text" class="small_15" id="borderWidth"
																		value="1px" /><span></span></label>
												</td>
												<td>
														<label>Border-Color: </label>
												</td>
										</tr>
										<tr>
												<td>
														<div id="slider_borderWidth" class="slider border"></div>
												</td>
												<td><input type="text" id="borderColor" class="color" maxlength="6px" value="006699" /></td>
										</tr>
										<tr>
												<td width="50%">
														<label>Border-Radius: <input type="text" class="small_15" id="borderRadius"
																		value="3px" /><span></span></label>
												</td>
												<td>
														<label>#Cols / #Rows: </label>

												</td>
										</tr>

										<tr>
												<td>
														<div id="slider_borderRadius" class="slider radius"></div>
												</td>
												<td>
														<input type="text" width="35" class="small_25_w" id="tCols" value="4" /> / <input
																type="text" width="35" class="small_25_w" id="tRows" value="5" /> <i
																style="font-size: 11px;">(for output only)</i>
												</td>
										</tr>
										<tr>
												<td width="50%">
														<label>CellPadding T/B: <input type="text" class="small_15" id="tbodyCellPadding_tb"
																		value="3px" /></label>
												</td>
												<td>
														<label>CellPadding L/R: <input type="text" class="small_15" id="tbodyCellPadding_lr"
																		value="10px" /></label>
												</td>
										</tr>
										<tr>
												<td>
														<div id="slider_tbodyCellPadding_tb" class="slider padding"></div>
												</td>
												<td>
														<div id="slider_tbodyCellPadding_lr" class="slider padding"></div>
												</td>
										</tr>
								</table>
						</div>

						<h2><input type="checkbox" id="thead" checked="checked" /><span>Table Header</span></h2>
						<div id="thead-box">
								<table width="100%" style="text-align: left;">
										<tr>
												<td colspan="2">&nbsp;
												</td>
										</tr>

										<tr>
												<td width="50%">
														<label>Font-Size:
																<input type="text" class="small_15" id="theadFontSize" value="15px" />
																<span></span>
														</label>
														<div class="bold-box">
																<input type="checkbox" id="theadBold" checked="checked" /><span>Bold</span>
														</div>
												</td>
												<td><label>Font-Color: </label></td>
										</tr>
										<tr>
												<td>
														<div id="slider_theadFontSize" class="slider fontsize"></div>
												</td>
												<td><input type="text" id="theadFontColor" class="color" maxlength="6px" value="ffffff" />
												</td>
										</tr>

										<tr>
												<td><label>TopGradientColor: </label></td>
												<td><label>BottomGradientColor: </label></td>
										</tr>
										<tr>
												<td><input type="text" id="theadBottomGradientColor" class="color" maxlength="6px"
																value="006699" /></td>
												<td><input type="text" id="theadTopGradientColor" class="color" maxlength="6px"
																value="00557F" /></td>
										</tr>
										<tr>
												<td colspan="2" style="border-top: 1px solid #5C5C5C; padding-top: 8px;">
														<div class="tbLine">
																<label>Column Lines: </label>
																<div class="bold-box" style="float: right; margin-right: 175px;">
																		<input type="checkbox" id="theadColLines" class="cboxTr"
																				checked="checked" /><span>Yes</span>
																</div>
														</div>
												</td>
										</tr>
										<tr class="theadColLines-box" style="display: none;">
												<td><label>Column-Line-Width: <input type="text" class="small_15" id="theadColLineWidth"
																		value="1px" /></label></td>
												<td><label>Column-Line-Color: </label></td>
										</tr>
										<tr class="theadColLines-box" style="display: none;">
												<td>
														<div id="slider_theadColLineWidth" class="slider border"></div>
												</td>
												<td><input type="text" id="theadColLineColor" class="color" maxlength="6" value="0070A8" />
												</td>
										</tr>
								</table>
						</div>
						<h2><span>Table Body</span></h2>
						<div id="tbody-box">
								<table width="100%" style="text-align: left;">
										<tr>
												<td colspan="2">&nbsp;
												</td>
										</tr>
										<tr>
												<td width="50%">
														<label>Font-Size: <input type="text" class="small_15" id="tbodyFontSize"
																		value="12px" /></label>
														<div class="bold-box">
																<input type="checkbox" id="tbodyBold" /><span>Bold</span>
														</div>
												</td>
												<td><label>Font-Color: </label></td>
										</tr>
										<tr>
												<td>
														<div id="slider_tbodyFontSize" class="slider fontsize"></div>
												</td>
												<td><input type="text" id="tbodyFontColor" class="color" maxlength="6" value="00496B" />
												</td>
										</tr>
										<!-- tBody Column Lines -->
										<tr>
												<td colspan="2" style="border-top: 1px solid #5C5C5C; padding-top: 8px;">
														<div class="tbLine">
																<label>Column Lines: </label>
																<div class="bold-box" style="float: right; margin-right: 175px;">
																		<input type="checkbox" id="tbodyColLines" class="cboxTr"
																				checked="checked" /><span>Yes</span>
																</div>
														</div>
												</td>
										</tr>
										<tr class="tbodyColLines-box" style="display: none;">
												<td><label>Column-Line-Width: <input type="text" class="small_15" id="tbodyColLineWidth"
																		value="1px" /></label></td>
												<td><label>Column-Line-Color: </label></td>
										</tr>
										<tr class="tbodyColLines-box" style="display: none;">
												<td>
														<div id="slider_tbodyColLineWidth" class="slider border"></div>
												</td>
												<td><input type="text" id="tbodyColLineColor" class="color" maxlength="6" value="E1EEF4" />
												</td>
										</tr>
										<!-- tBody Row Lines -->
										<tr>
												<td colspan="2" style="border-top: 1px solid #5C5C5C; padding-top: 8px;">
														<div class="tbLine">
																<label>Row Lines: </label>
																<div class="bold-box" style="float: right; margin-right: 175px;">
																		<input type="checkbox" id="tbodyRowLines" class="cboxTr" /><span>Yes</span>
																</div>
														</div>
												</td>
										</tr>
										<tr class="tbodyRowLines-box" style="display: none;">
												<td><label>Row-Line-Width: <input type="text" class="small_15" id="tbodyRowLineWidth"
																		value="1px" /></label></td>
												<td><label>Row-Line-Color: </label></td>
										</tr>
										<tr class="tbodyRowLines-box" style="display: none;">
												<td>
														<div id="slider_tbodyRowLineWidth" class="slider border"></div>
												</td>
												<td><input type="text" id="tbodyRowLineColor" class="color" maxlength="6" value="E1EEF4" />
												</td>
										</tr>
										<!-- tBody Alt Rows -->
										<tr>
												<td colspan="2" style="border-top: 1px solid #5C5C5C; padding-top: 8px;">
														<div class="tbLine">
																<label>Alternate Rows: </label>
																<div class="bold-box" style="float: right; margin-right: 175px;">
																		<input type="checkbox" id="tbodyAltRows" class="cboxTr"
																				checked="checked" /><span>Yes</span>
																</div>
														</div>
												</td>
										</tr>
										<tr class="tbodyAltRows-box" style="display: none;">
												<td><label>Alt-Font-Color: </label></td>
												<td><label>Alt-Background-Color: </label></td>
										</tr>
										<tr class="tbodyAltRows-box" style="display: none;">
												<td><input type="text" id="tbodyAltFontColor" class="color" maxlength="6px"
																value="00496B" /></td>
												<td><input type="text" id="tbodyAltBackgroundColor" class="color" maxlength="6px"
																value="E1EEF4" /></td>
										</tr>
								</table>
						</div>
						<h2><input type="checkbox" id="tfoot" checked="checked" /><span>Table Footer</span></h2>
						<div id="tfoot-box">
								<table width="100%" style="text-align: left;">
										<tr>
												<td colspan="2">&nbsp;
												</td>
										</tr>
										<tr>
												<td width="50%">
														<label>Font-Size: <input type="text" class="small_15" id="tfootFontSize"
																		value="12px" /></label>
														<div class="bold-box">
																<input type="checkbox" id="tfootBold" /><span>Bold</span>
														</div>
												</td>
												<td><label>Font-Color: </label></td>
										</tr>
										<tr>
												<td>
														<div id="slider_tfootFontSize" class="slider fontsize"></div>
												</td>
												<td><input type="text" id="tfootFontColor" class="color" maxlength="6" value="00496B" />
												</td>
										</tr>
										<tr>
												<td width="50%">
														<label>Footer Padding: <input type="text" class="small_15" id="tfootPadding"
																		value="2px" /></label>
												</td>
												<td><label>Background-Color: </label></td>
										</tr>
										<tr>
												<td>
														<div id="slider_tfootPadding" class="slider padding"></div>
												</td>
												<td><input type="text" id="tfootBackgroundColor" class="color" maxlength="6px"
																value="E1EEF4" /></td>
										</tr>
										<tr>
												<td colspan="2" style="border-top: 1px solid #5C5C5C; padding-top: 8px;">
														<div class="tbLine">
																<label>Pagination: </label>
																<div class="bold-box" style="float: right; margin-right: 175px;">
																		<input type="checkbox" id="tfootPaging" class="cboxTr"
																				checked="checked" /><span>Yes</span>
																</div>
														</div>
												</td>
										</tr>
										<tr class="tfootPaging-box">
												<td width="50%">
														<label>Border-Size: <input type="text" class="small_15" id="tfootPagingBorderWidth"
																		value="1px" /><span></span></label>
												</td>
												<td>
														<label>Border-Radius: <input type="text" class="small_15" id="tfootPagingBorderRadius"
																		value="3px" /><span></span></label>
												</td>
										</tr>
										<tr class="tfootPaging-box">
												<td width="50%">
														<div id="slider_tfootPagingBorderWidth" class="slider border"></div>
												</td>
												<td>
														<div id="slider_tfootPagingBorderRadius" class="slider radius"></div>
												</td>
										</tr>



										<!-- footer font color -->
										<tr class="tfootPaging-box">
												<td><label>Font-Color: </label></td>
												<td><label>Active Font Color: </label></td>
										</tr>
										<tr class="tfootPaging-box">
												<td><input type="text" id="tfootPagingFontColor" class="color" maxlength="6px"
																value="FFFFFF" /></td>
												<td><input type="text" id="tfootPagingActiveFontColor" class="color" maxlength="6px"
																value="FFFFFF" /></td>
										</tr>

										<!-- footer Border color -->
										<tr class="tfootPaging-box">
												<td><label>Border-Color: </label></td>
												<td><label>Active Border Color: </label></td>

										</tr>
										<tr class="tfootPaging-box">
												<td width="50%"><input type="text" id="tfootPagingBorderColor" class="color" maxlength="6px"
																value="006699" /></td>
												<td><input type="text" id="tfootPagingActiveBorderColor" class="color" maxlength="6px"
																value="006699" /></td>
										</tr>

										<!-- foot top gradient color -->
										<tr class="tfootPaging-box">
												<td><label>TopGradientColor: </label></td>
												<td><label>Active BG Color: </label></td>
										</tr>
										<tr class="tfootPaging-box">
												<td><input type="text" id="tfootPagingTopGradientColor" class="color" maxlength="6px"
																value="006699" /></td>
												<td><input type="text" id="tfootPagingActiveBackgroundColor" class="color" maxlength="6px"
																value="00557F" /></td>
										</tr>

										<!-- foot Bottom gradient color -->
										<tr class="tfootPaging-box">
												<td><label>BottomGradientColor: </label></td>
												<td>&nbsp;</td>
										</tr>
										<tr class="tfootPaging-box">
												<td><input type="text" id="tfootPagingBottomGradientColor" class="color" maxlength="6px"
																value="00557F" /></td>
												<td>&nbsp;</td>
										</tr>

								</table>
						</div>

						<div style="height: 50px;">
								&nbsp;
						</div>

				</form>
		</div>

		<div id="mainContent">
				<div style="padding: 180px 5px 20px; line-height: 150%;">

						&nbsp;
				</div>
				<div id="fixedCont">
						<div id="tableCont" class="tableCont">
								<div class="fb-like" data-href="http://tablestyler.com" data-send="false" data-layout="box_count"
										data-width="450" data-show-faces="false"></div>
								<div
										style="padding-left: 5px; text-align: left; padding-right: 25px; margin-top: -4px; margin-bottom: 2px;">

								</div>
								<div class="box">
										<div id="box-menu">
												<div id="menu_cont" style="display: none;">
														<div id="html" style="display: none;">
																<textarea>html</textarea>
														</div>
														<div id="css" style="display: none;">
																<textarea>css</textarea>
														</div>
												</div>
												<ul class="hzmenu">
														<li><a id="html_btn" href="#">HTML</a></li>
														<li><a id="css_btn" href="#">CSS</a></li>
												</ul>
										</div>
										<div id="all" class="datagrid" style="margin-top: 33px;">
												<table>
														<thead>
																<tr>
																		<th>Title</th>
																		<th>Column 1</th>
																		<th>Column 2</th>
																		<th>Column 3</th>
																</tr>
														</thead>
														<tfoot>
																<tr>
																		<td colspan="4">
																				<div id="no-paging" style="display: none;">&nbsp;</div>
																				<div id="paging">
																						<ul>
																								<li><a href="#"><span>Previous</span></a></li>
																								<li><a href="#" class="active"><span>1</span></a></li>
																								<li><a href="#"><span>2</span></a></li>
																								<li><a href="#"><span>3</span></a></li>
																								<li><a href="#"><span>4</span></a></li>
																								<li><a href="#"><span>5</span></a></li>
																								<li><a href="#"><span>Next</span></a></li>
																						</ul>
																				</div>
																		</td>
																</tr>
														</tfoot>
														<tbody>
																<tr>
																		<td>Row 1</td>
																		<td>data 1</td>
																		<td>data 2</td>
																		<td>data 3</td>
																</tr>
																<tr class="alt">
																		<td>Row 1</td>
																		<td>data 1</td>
																		<td>data 2</td>
																		<td>data 3</td>
																</tr>
																<tr>
																		<td>Row 1</td>
																		<td>data 1</td>
																		<td>data 2</td>
																		<td>data 3</td>
																</tr>
																<tr class="alt">
																		<td>Row 1</td>
																		<td>data 1</td>
																		<td>data 2</td>
																		<td>data 3</td>
																</tr>
																<tr>
																		<td>Row 1</td>
																		<td>data 1</td>
																		<td>data 2</td>
																		<td>data 3</td>
																</tr>
														</tbody>
												</table>
										</div>
								</div>
						</div>
						<div style="padding: 5px 10px;">Questions, Comments or Suggestions? Join the <a class="pageLink"
										href="http://eligeske.com/cool-web-stuff/data-table-style-generator/"
										alt="Table Generator Discussion">Table Generator Discussion Here</a>.</div>
						<div id="theme-box" style="padding: 0 10px;">
								<div>
										<div id="theme1" class='theme-box'>
												<div class='th_theme'>
														<div>&nbsp;</div>
												</div>
												<div class='tr_theme'>
														<div>&nbsp;</div>
												</div>
												<div class='tr_alt_theme'>
														<div>&nbsp;</div>
												</div>
										</div>
										<div id="theme2" class='theme-box'>
												<div class='th_theme'>
														<div>&nbsp;</div>
												</div>
												<div class='tr_theme'>
														<div>&nbsp;</div>
												</div>
												<div class='tr_alt_theme'>
														<div>&nbsp;</div>
												</div>
										</div>
										<div id="theme3" class='theme-box'>
												<div class='th_theme'>
														<div>&nbsp;</div>
												</div>
												<div class='tr_theme'>
														<div>&nbsp;</div>
												</div>
												<div class='tr_alt_theme'>
														<div>&nbsp;</div>
												</div>
										</div>
										<div id="theme4" class='theme-box'>
												<div class='th_theme'>
														<div>&nbsp;</div>
												</div>
												<div class='tr_theme'>
														<div>&nbsp;</div>
												</div>
												<div class='tr_alt_theme'>
														<div>&nbsp;</div>
												</div>
										</div>
										<div id="theme5" class='theme-box'>
												<div class='th_theme'>
														<div>&nbsp;</div>
												</div>
												<div class='tr_theme'>
														<div>&nbsp;</div>
												</div>
												<div class='tr_alt_theme'>
														<div>&nbsp;</div>
												</div>
										</div>
										<div id="theme6" class='theme-box'>
												<div class='th_theme'>
														<div>&nbsp;</div>
												</div>
												<div class='tr_theme'>
														<div>&nbsp;</div>
												</div>
												<div class='tr_alt_theme'>
														<div>&nbsp;</div>
												</div>
										</div>
										<!--
			<ul class="color_themes">
					<li>
							<div id="theme_1" class="theme">
									<span class='th_color' style="background-color: #006699">&nbsp;</span>
									<span class='th_color' style="background-color: #FFFFFF">&nbsp;</span>
										<span class='th_color' style="background-color: #E1EEF4">&nbsp;</span>
										<span class='th_color' style="background-color: #00557F">&nbsp;</span>
								</div>
						</li>
						<li>
							<div id="theme_2" class="theme">
									<span class='th_color' style="background-color: #006699">&nbsp;</span>
									<span class='th_color' style="background-color: #FFFFFF">&nbsp;</span>
										<span class='th_color' style="background-color: #E1EEF4">&nbsp;</span>
										<span class='th_color' style="background-color: #00557F">&nbsp;</span>
								</div>
						</li>
				</ul>
				-->
								</div>
						</div>
				</div>
		</div>
		<!-- This clearing element should immediately follow the #mainContent div in order to force the #container div to contain all child floats --><br
				class="clearfloat" />
		<!-- end #container -->
					`
				}}
		
		>

		</div>
	</React.Fragment>
}

export default HomePage